name: oauth_verify_shelf
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/damondouglas/oauth_verify_shelf
author: Damon Douglas <douglas.damon@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
dependencies:
  shelf: '^0.6.7+2'
  http: '>=0.11.1 <0.12.0'
  googleapis: '^0.36.0'
